version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: user_profile_mongodb
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - /data/db/mongodb/user-profile:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-profile-converter
    depends_on:
      - mongodb
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ~/code/go/src/github.com/yshujie/user-profile-converter:/app  # 挂载宿主机的项目目录到容器内
    env_file:
      - .env

  init:
    image: golang:1.18-alpine
    volumes:
      - ~/code/go/src/github.com/yshujie/user-profile-converter:/app
    working_dir: /app
    command: sh -c "go mod tidy && go mod download"