version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ~/code/go/src/github.com/yshujie/user-profile-converter:/app
      - ～code/go/pkg/mod:/go/pkg/mod
    command: air -c .air.toml