version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: user_profile_mongodb
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - /data/db/mongodb/user-profile:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-profile-converter
    depends_on:
      - mongodb
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env